export enum CountriesActionTypes {
    FETCH_COUNTRIES = 'FETCH_COUNTRIES',
    FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START',
    FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS',
    FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR',
}